### ISSUE TITLE
jgkamat/locale:14.04.2 can't find bash

### ISSUE THREAD

**Issue by justbuchanan** [jgkamat/dockerfiles#1]
When I do `sudo docker run -t -i jgkamat/locale:14.04.2 /bin/bash`, I get:

``` .sh
docker: Error response from daemon: Container command '/bin/bash' not found or does not exist..
 %  
```

I pulled the latest before running, so I should be up-to-date.  Any ideas?

**Comment by jgkamat** [comment]
I cant seem to reproduce this on my machine. The image was updated 3 days ago (builds trigger when library/ubuntu is changed), so I don't think we have a version mismatch. Does this happen with ubuntu:14.04.2? The dockerfile is only running [one command](https://github.com/jgkamat/dockerfiles/blob/master/Locales/14.04.2/Dockerfile)... This dosent impact anything in our CI setup right?

Does `docker run -ti jgkamat/locale:14.04.2 sh` work for you? That should work in any case.

Also, which docker version are you running? The docker has been making some backwards incompatible changes (but those should be in the pulls, not in the actual execution...)

If you can still reproduce this, I think that this should probably be reported to docker/docker.

![snapshot130](https://cloud.githubusercontent.com/assets/4349709/15843993/64b58158-2c1b-11e6-9b87-454b0d8fe3d8.png)

**Comment by justbuchanan** [comment]
Ok, thanks for the info!

I tried it on my laptop and it works fine - it seems to only fail on my desktop :confused:.  Both are on the same version of docker and are updated to the latest and greatest everything, so I'm not sure what's up.  I'll report it to docker then and see what they say.

**Comment by jgkamat** [comment]
definetly post the issue here once you report it. One more thing, could you try:
`sh -c 'sudo docker run -t -i jgkamat/locale:14.04.2 /bin/bash'`

That should make sure that there are no aliases/shell parsing  that could be messing with it. 

Also, check `docker info` and see if there are any differences. most of those settings shouldnt matter but I've had a few issues in the past which that helped. I still couldn't imagine what could be causing this though... :P

**Comment by justbuchanan** [comment]
Sounds good.  I'm away from the non-working computer now, but I'll investigate further tomorrow and see what I can find.  I haven't messed with aliases or settings that I recall, but anything's possible :)

**Comment by justbuchanan** [comment]
I messed around with this some more and after a reboot, everything works great!   It does seem like a docker bug, but I don't really have enough info to file a helpful bug report.
